# Generated by Django 6.0.3 on 2026-05-09 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="学校名称")),
            ],
            options={
                "verbose_name": "学校",
                "verbose_name_plural": "学校",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="任务代码"),
                ),
                ("power_reward", models.IntegerField(default=10, verbose_name="奖励体力")),
                (
                    "icon",
                    models.CharField(default="⭐", max_length=10, verbose_name="图标"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("nickname", models.CharField(max_length=50, verbose_name="昵称")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男孩"), ("F", "女孩")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        default="default", max_length=20, verbose_name="头像"
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="勇士等级")),
                ("power", models.IntegerField(default=0, verbose_name="当前体力值")),
                (
                    "power_to_next",
                    models.IntegerField(default=40, verbose_name="升级所需体力"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联家长",
                    ),
                ),
            ],
            options={
                "verbose_name": "孩子",
                "verbose_name_plural": "孩子们",
            },
        ),
        migrations.CreateModel(
            name="Encouragement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="鼓励内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encouragements",
                        to="core.child",
                        verbose_name="孩子",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encouragements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "鼓励语",
                "verbose_name_plural": "鼓励语",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=50, verbose_name="班级名称")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="core.school",
                        verbose_name="学校",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "老师",
                "verbose_name_plural": "老师们",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="活动标题")),
                ("content", models.TextField(verbose_name="活动内容")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("challenge", "健康挑战"),
                            ("competition", "班级比赛"),
                            ("education", "健康教育"),
                        ],
                        default="challenge",
                        max_length=20,
                        verbose_name="活动类型",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.teacher",
                        verbose_name="发布老师",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动",
                "verbose_name_plural": "活动",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("completed", "已完成"),
                            ("confirmed", "已确认"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_records",
                        to="core.child",
                        verbose_name="孩子",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.task",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务记录",
                "verbose_name_plural": "任务记录",
                "ordering": ["-date", "-submitted_at"],
                "unique_together": {("child", "task", "date")},
            },
        ),
        migrations.CreateModel(
            name="ClassStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to="core.child",
                        verbose_name="孩子",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="core.teacher",
                        verbose_name="老师",
                    ),
                ),
            ],
            options={
                "verbose_name": "班级学生",
                "verbose_name_plural": "班级学生",
                "unique_together": {("teacher", "child")},
            },
        ),
    ]
