# Generated by Django 6.0.3 on 2026-05-09 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="bind_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="绑定码"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联家长",
            ),
        ),
    ]
