# Generated by Django 6.0.3 on 2026-05-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_child_bind_code_alter_child_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="徽章名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="徽章代码"),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("nutrition", "营养达人"),
                            ("exercise", "运动健将"),
                            ("sleep", "作息标兵"),
                            ("hygiene", "卫生之星"),
                            ("challenge", "挑战英雄"),
                            ("streak", "坚持勋章"),
                        ],
                        default="nutrition",
                        max_length=20,
                        verbose_name="徽章类型",
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🏅", max_length=50, verbose_name="徽章图标"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="徽章描述"),
                ),
                (
                    "requirement",
                    models.IntegerField(default=1, verbose_name="解锁条件(数值)"),
                ),
                ("power_reward", models.IntegerField(default=20, verbose_name="体力奖励")),
            ],
            options={
                "verbose_name": "成就徽章",
                "verbose_name_plural": "成就徽章",
            },
        ),
        migrations.CreateModel(
            name="FoodMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="食材名称"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("grain", "谷物类"),
                            ("protein", "蛋白质类"),
                            ("vegetable", "蔬菜类"),
                            ("fruit", "水果类"),
                            ("dairy", "乳制品类"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="食材类别",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "红-谷物"),
                            ("yellow", "黄-蛋白质"),
                            ("green", "绿-蔬菜"),
                            ("blue", "蓝-水果"),
                            ("purple", "紫-乳制品"),
                        ],
                        max_length=10,
                        verbose_name="五色分类",
                    ),
                ),
                ("protein", models.FloatField(default=0, verbose_name="蛋白质(g/100g)")),
                (
                    "carbohydrate",
                    models.FloatField(default=0, verbose_name="碳水化合物(g/100g)"),
                ),
                ("fat", models.FloatField(default=0, verbose_name="脂肪(g/100g)")),
                ("fiber", models.FloatField(default=0, verbose_name="膳食纤维(g/100g)")),
                (
                    "calories",
                    models.FloatField(default=0, verbose_name="热量(kcal/100g)"),
                ),
                (
                    "image_url",
                    models.CharField(blank=True, max_length=200, verbose_name="食材图片"),
                ),
                (
                    "yolo_class",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="YOLO识别类别"
                    ),
                ),
            ],
            options={
                "verbose_name": "食材",
                "verbose_name_plural": "食材库",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="食谱名称")),
                ("description", models.TextField(blank=True, verbose_name="食谱描述")),
                ("ingredients", models.TextField(verbose_name="食材清单")),
                ("steps", models.TextField(blank=True, verbose_name="烹饪步骤")),
                ("calories", models.FloatField(default=0, verbose_name="热量(kcal)")),
                ("protein", models.FloatField(default=0, verbose_name="蛋白质(g)")),
                ("carbohydrate", models.FloatField(default=0, verbose_name="碳水化合物(g)")),
                ("fat", models.FloatField(default=0, verbose_name="脂肪(g)")),
                (
                    "suitable_for",
                    models.CharField(blank=True, max_length=50, verbose_name="适宜人群"),
                ),
                (
                    "target_nutrients",
                    models.CharField(blank=True, max_length=100, verbose_name="补充营养"),
                ),
                (
                    "image_url",
                    models.CharField(blank=True, max_length=200, verbose_name="食谱图片"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "食谱",
                "verbose_name_plural": "食谱推荐",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="child",
            name="gem_blue",
            field=models.BooleanField(default=False, verbose_name="蓝色水果宝石"),
        ),
        migrations.AddField(
            model_name="child",
            name="gem_green",
            field=models.BooleanField(default=False, verbose_name="绿色蔬菜宝石"),
        ),
        migrations.AddField(
            model_name="child",
            name="gem_purple",
            field=models.BooleanField(default=False, verbose_name="紫色乳制品宝石"),
        ),
        migrations.AddField(
            model_name="child",
            name="gem_red",
            field=models.BooleanField(default=False, verbose_name="红色谷物宝石"),
        ),
        migrations.AddField(
            model_name="child",
            name="gem_yellow",
            field=models.BooleanField(default=False, verbose_name="黄色蛋白质宝石"),
        ),
        migrations.CreateModel(
            name="HealthChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="挑战标题")),
                ("description", models.TextField(verbose_name="挑战说明")),
                (
                    "challenge_type",
                    models.CharField(max_length=30, verbose_name="挑战类型"),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                ("target_value", models.IntegerField(default=7, verbose_name="目标值")),
                (
                    "power_reward",
                    models.IntegerField(default=50, verbose_name="完成奖励体力"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("completed", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="core.teacher",
                        verbose_name="发布老师",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康挑战",
                "verbose_name_plural": "健康挑战赛",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MealRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "早餐"),
                            ("lunch", "午餐"),
                            ("dinner", "晚餐"),
                            ("snack", "零食/加餐"),
                        ],
                        max_length=20,
                        verbose_name="餐次",
                    ),
                ),
                (
                    "image_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="图片存储KEY"
                    ),
                ),
                ("total_score", models.IntegerField(default=0, verbose_name="五色评分")),
                ("total_calories", models.FloatField(default=0, verbose_name="总热量")),
                ("total_protein", models.FloatField(default=0, verbose_name="总蛋白质")),
                (
                    "total_carbohydrate",
                    models.FloatField(default=0, verbose_name="总碳水"),
                ),
                ("total_fat", models.FloatField(default=0, verbose_name="总脂肪")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否人工确认"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_records",
                        to="core.child",
                        verbose_name="孩子",
                    ),
                ),
            ],
            options={
                "verbose_name": "膳食记录",
                "verbose_name_plural": "膳食记录",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("child", "date", "meal_type")},
            },
        ),
        migrations.CreateModel(
            name="MealFoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=100, verbose_name="预估重量(g)")),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.foodmaterial",
                        verbose_name="食材",
                    ),
                ),
                (
                    "meal_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to="core.mealrecord",
                        verbose_name="膳食记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "膳食食材",
                "verbose_name_plural": "膳食食材明细",
            },
        ),
        migrations.CreateModel(
            name="ChildBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获得时间"),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.badge",
                        verbose_name="徽章",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="core.child",
                        verbose_name="孩子",
                    ),
                ),
            ],
            options={
                "verbose_name": "孩子徽章",
                "verbose_name_plural": "孩子徽章",
                "unique_together": {("child", "badge")},
            },
        ),
        migrations.CreateModel(
            name="ChallengeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.IntegerField(default=0, verbose_name="当前进度")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_progress",
                        to="core.child",
                        verbose_name="孩子",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="core.healthchallenge",
                        verbose_name="挑战",
                    ),
                ),
            ],
            options={
                "verbose_name": "挑战进度",
                "verbose_name_plural": "挑战进度",
                "unique_together": {("challenge", "child")},
            },
        ),
    ]
