# Generated by Django 6.0.3 on 2026-05-10 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_badge_foodmaterial_recipe_child_gem_blue_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
    ]
