# Generated by Django 6.0.3 on 2026-05-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_user_to_child"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("steps", models.IntegerField(default=0, verbose_name="步数")),
                ("step_goal", models.IntegerField(default=8000, verbose_name="步数目标")),
                ("active_minutes", models.IntegerField(default=0, verbose_name="活动分钟")),
                ("calories_burned", models.FloatField(default=0, verbose_name="消耗卡路里")),
                ("heart_rate_avg", models.IntegerField(default=0, verbose_name="平均心率")),
                ("heart_rate_max", models.IntegerField(default=0, verbose_name="最大心率")),
                ("heart_rate_min", models.IntegerField(default=0, verbose_name="最小心率")),
                (
                    "sleep_duration_minutes",
                    models.IntegerField(default=0, verbose_name="睡眠时长(分钟)"),
                ),
                (
                    "deep_sleep_minutes",
                    models.IntegerField(default=0, verbose_name="深睡时长"),
                ),
                (
                    "light_sleep_minutes",
                    models.IntegerField(default=0, verbose_name="浅睡时长"),
                ),
                (
                    "rem_sleep_minutes",
                    models.IntegerField(default=0, verbose_name="REM时长"),
                ),
                (
                    "last_sync",
                    models.DateTimeField(auto_now=True, verbose_name="最后同步时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_data",
                        to="core.child",
                        verbose_name="孩子",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康数据",
                "verbose_name_plural": "健康数据",
                "unique_together": {("child", "date")},
            },
        ),
    ]
