# Generated by Django 6.0.3 on 2026-05-11 07:45
# Renumbered from 0006_school_campus_hub after merging migration branches.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_health_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthchallenge",
            name="reward_description",
            field=models.TextField(blank=True, verbose_name="奖励说明"),
        ),
        migrations.AddField(
            model_name="healthchallenge",
            name="rule_description",
            field=models.TextField(blank=True, verbose_name="自定义规则说明"),
        ),
        migrations.AddField(
            model_name="healthchallenge",
            name="scope",
            field=models.CharField(
                choices=[("class", "本班"), ("school", "校级")],
                default="class",
                max_length=20,
                verbose_name="发起范围",
            ),
        ),
        migrations.AddField(
            model_name="healthchallenge",
            name="summary_report",
            field=models.TextField(blank=True, verbose_name="结束后总结报告"),
        ),
        migrations.CreateModel(
            name="HealthCourseResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="资源标题")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("article", "图文科普"),
                            ("video", "短视频"),
                            ("ppt", "课件资料"),
                            ("mixed", "混合"),
                        ],
                        default="article",
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                ("content", models.TextField(blank=True, verbose_name="正文或导读")),
                ("media_url", models.CharField(blank=True, max_length=500, verbose_name="视频/附件链接")),
                ("unlock_requires_task", models.BooleanField(default=True, verbose_name="需健康打卡后解锁")),
                ("pushed_at", models.DateTimeField(blank=True, null=True, verbose_name="推送时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_resources",
                        to="core.teacher",
                        verbose_name="发布老师",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康课程资源",
                "verbose_name_plural": "健康课程资源",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolHealthArchive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="归档标题")),
                ("snapshot_json", models.TextField(verbose_name="统计数据快照(JSON)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="归档时间")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_archives",
                        to="core.teacher",
                        verbose_name="老师",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康教育归档",
                "verbose_name_plural": "健康教育归档",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolHomeMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="主题")),
                ("body", models.TextField(verbose_name="沟通要点")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录时间")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_messages",
                        to="core.teacher",
                        verbose_name="老师",
                    ),
                ),
            ],
            options={
                "verbose_name": "家校沟通",
                "verbose_name_plural": "家校沟通",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthResourceUnlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unlocked_at", models.DateTimeField(auto_now_add=True, verbose_name="解锁时间")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_unlocks",
                        to="core.child",
                        verbose_name="孩子",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="core.healthcourseresource",
                        verbose_name="资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源解锁记录",
                "verbose_name_plural": "资源解锁记录",
                "unique_together": {("resource", "child")},
            },
        ),
    ]
